# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: NPM CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: NPM Install
      run: npm ci
    - name: NPM Build
      run: npm run build --if-present
 #   - name: NPM test
 #     run: npm test
    - name: Build tar
      run: tar -czvf /tmp/nlp.js-server.tar.gz .
    - name: Stop NLP.js service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CD_HOST }}
        username: ${{ secrets.CD_USERNAME }}
        password: ${{ secrets.CD_PASSWORD }}
        script: systemctl stop nlp-js.service
    - name: Uploading new version
      uses: garygrossgarten/github-action-scp@release
      with:
        local: /tmp/nlp.js-server.tar.gz
        remote: /tmp/nlp.js-server.tar.gz
        host: ${{ secrets.CD_HOST }}
        username: ${{ secrets.CD_USERNAME }}
        password: ${{ secrets.CD_PASSWORD }}
        rmRemote: true
    - name: Unpackage tar
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CD_HOST }}
        username: ${{ secrets.CD_USERNAME }}
        password: ${{ secrets.CD_PASSWORD }}
        script: rm -rf /home/gdaniel/repositories/nlp.js-server/* && tar -xvf /tmp/nlp.js-server.tar.gz -C /home/gdaniel/repositories/nlp.js-server
    - name: Restart NLP.js service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CD_HOST }}
        username: ${{ secrets.CD_USERNAME }}
        password: ${{ secrets.CD_PASSWORD }}
        script: systemctl start nlp-js.service
        
        
        
