# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: NPM CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: NPM Install
      run: npm ci
    - name: NPM Build
      run: npm run build --if-present
 #   - name: NPM test
 #     run: npm test
    - name: Stopping NLP.js service
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sudo systemctl stop nlp-js.service
        host: ${{ secrets.CD_HOST }}
        username: gdaniel
        password: ${{ secrets.CD_PASSWORD }}
        
